project_id = "mgqtafcaerqqfkkytadf"

[auth]
enabled = true
site_url = "http://localhost:5173"

[functions.send-task-reminder]
verify_jwt = false

[functions.check-task-reminders]
verify_jwt = false

[functions.task-recommendations]
verify_jwt = true