// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgqtafcaerqqfkkytadf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ncXRhZmNhZXJxcWZra3l0YWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDIxMDcsImV4cCI6MjA2NDg3ODEwN30._mH04GLiBD9N0ldryyhRbO0esoBxksZZLKsAjjPtjsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);